version: '3.8'

services:
  otrust-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otrust-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_URI=mongodb://otrust-mongodb:27017/otrust
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_change_me}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - BLOCKCHAIN_PATH=/app/data/blockchain
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    volumes:
      - otrust-blockchain:/app/data/blockchain
      - otrust-logs:/app/logs
    depends_on:
      - otrust-mongodb
    networks:
      - otrust-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  otrust-mongodb:
    image: mongo:6
    container_name: otrust-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER:-}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-}
    volumes:
      - otrust-mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - otrust-network
    command: ["--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  otrust-mongodb-data:
    name: otrust-mongodb-data
  otrust-blockchain:
    name: otrust-blockchain
  otrust-logs:
    name: otrust-logs

networks:
  otrust-network:
    name: otrust-network
    driver: bridge
